### ISSUE TITLE
报错 manifest unknown

### ISSUE THREAD

**Issue by hiblacker** [VariantConst/OpenWebUI-Monitor#6]
<img width="773" alt="image" src="https://github.com/user-attachments/assets/6fa8dadf-7691-4737-938b-f42f6880684a">

大佬 执行 sudo docker compose up -d时，报错manifest unknown

**Comment by CatechumenLee** [comment]
我也一样 https://github.com/jlelse/GoBlog/issues/60 找到一个类似的issue，解决方案是删除 GH 操作缓存并添加

provenance: false

**Comment by CatechumenLee** [comment]
@VariantConst

**Comment by VariantConst** [comment]
已修
