### ISSUE TITLE
无法正常加载模型管理界面

### ISSUE THREAD

**Issue by U4F5Va6c** [VariantConst/OpenWebUI-Monitor#7]
在点击进入页面之后，无法加载页面，同时浏览器后台报错
<img width="2305" alt="image" src="https://github.com/user-attachments/assets/a5ab4e3a-2ee2-4a13-8c46-998934d605af">
进入monitor的/api/v1/models后输出
`{"error":"Cannot convert argument to a ByteString because the character at index 58 has a value of 23494 which is greater than 255."}`
OpenWebUI的页面元素正常显示
<img width="612" alt="image" src="https://github.com/user-attachments/assets/dc99c4d3-179a-4b5f-a0e3-946e1821eafe">
使用统计也正常记录
<img width="1045" alt="image" src="https://github.com/user-attachments/assets/14486e8a-0069-4b4f-a6fc-60176947f448">
是不是因为我的模型太多的原因？
<img width="186" alt="image" src="https://github.com/user-attachments/assets/83e14449-0f19-403d-96f5-e5997d19365c">
以下是Docker的报错log
```
Error fetching models: TypeError: Cannot convert argument to a ByteString because the character at index 58 has a value of 23494 which is greater than 255.
at webidl.converters.ByteString (node:internal/deps/undici/undici:2053:17)
at Object.record (node:internal/deps/undici/undici:1963:32)
at webidl.converters.HeadersInit (node:internal/deps/undici/undici:2541:67)
at Object.RequestInit (node:internal/deps/undici/undici:2019:21)
at new Request (node:internal/deps/undici/undici:6091:34)
at i (/app/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:177224)
at E (/app/.next/server/app/api/v1/models/route.js:1:693)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async /app/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:42484
at async eI.execute (/app/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:32486)
```

**Comment by VariantConst** [comment]
能否通过 pastebin 提供 `curl -H "Authorization: Bearer $OPENWEBUI_API_KEY" https://your_openwebui_domain/api/models` 的结果文件？

**Comment by VariantConst** [comment]
建议在 pastebin 中隐藏敏感信息

**Comment by U4F5Va6c** [comment]
> 建议在 pastebin 中隐藏敏感信息

我意识到了这个问题但是我无法删除了，更改也不行，发布的时候是匿名，我想快点提交的，发布完了就发现请求指令都粘贴了，请问有删除的方法吗？我提交了举报不知道能不能删除，我使用的sk已经更换了，域名走的CF暂时应该没有太大问题

**Comment by U4F5Va6c** [comment]
> 能否通过 pastebin 提供 `curl -H "Authorization: Bearer $OPENWEBUI_API_KEY" https://your_openwebui_domain/api/models` 的结果文件？

这个无法加载的问题是我这边的个例，还是是bug？

**Comment by VariantConst** [comment]
可能是模型缩略图获取引起的一个 bug。我测试发现 OpenWebUI 的 /api/models 提供的模型缩略图字段都是 base64 的字符串，所以代码是这样写的：
`imageUrl: item.info?.meta?.profile_image_url || "/openwebui.png"`
但你这边该字段显示 `"profile_image_url": "/static/favicon.png"`，程序后续尝试获取该 `/static/favicon.png` 失败可能会导致该错误。

我推测你使用了比较老的 OpenWebUI 版本，API 接口有所不同？一个简单的验证方式是把所有模型都自定义一个头像，看看是否解决了问题。

**Comment by U4F5Va6c** [comment]
我可能解决这个问题了，我是通过清除浏览器的缓存解决的，感觉可能是本地什么数据冲突导致的，其实只要我换个浏览器就能正常访问，还有就是CF的网页缓存，导致我服务都关闭了但是服务的首页都能正常访问

**Comment by VariantConst** [comment]
1. 简单起见，token 验证目前是在客户端进行的。之后考虑更改为服务端认证；
2. 之前进行了短暂的版本回滚，正好被你碰到了，不是设置问题。

**Comment by VariantConst** [comment]
> 这样的话其实是token登录这种模式在cf上缓存后就会碰到这样的问题么？我现在只要打开小黄云，就可以直接管理，直连服务器就正常需要验证，这是在现在验证方式下正常的吗？
这是一个 bug，已在 v0.1.6 中修复。

> 还有你之前推测我使用的是老旧的openwebui，我使用的是最新的，我也是前几天才部署好的webui是0.4.7版本的。
是的，应该是 OpenWebUI 偷偷改 API 接口了，这个项目也不提供详细的 API 文档。v0.1.6 已经适配最新的 API 接口。

**Comment by U4F5Va6c** [comment]
> 这是一个 bug，已在 v0.1.6 中修复。

我更新了最新的镜像之后，直连服务器IP都会触发这个bug了，但是token确实存储在本地存储了，访问服务端口之后还是会进入管理界面，就算是清理了缓存或换浏览器也一样

**Comment by VariantConst** [comment]
> 我更新了最新的镜像之后，直连服务器IP都会触发这个bug了，但是token确实存储在本地存储了，访问服务端口之后还是会进入管理界面，就算是清理了缓存或换浏览器也一样

能否测试一下 dev 分支的最新提交，在本地自行 build，看看是否解决了问题？

**Comment by U4F5Va6c** [comment]
> > 我更新了最新的镜像之后，直连服务器IP都会触发这个bug了，但是token确实存储在本地存储了，访问服务端口之后还是会进入管理界面，就算是清理了缓存或换浏览器也一样
> 
> 能否测试一下 dev 分支的最新提交，在本地自行 build，看看是否解决了问题？

对不起，我没有在本地编译过docker镜像，并不知道如何操作，并且我暂时有些事情要忙，可能要晚些进行测试。如果可以的话请给我一个如何编译的指令，我知道需要从GitHub上pull仓库，之后只要在目录下运行docker compose up -d就行了么？

**Comment by VariantConst** [comment]
v0.1.7 应该解决了这个问题

**Comment by U4F5Va6c** [comment]
> v0.1.7 应该解决了这个问题

我刚好上线，马上就试一下

**Comment by U4F5Va6c** [comment]
> v0.1.7 应该解决了这个问题

我这边又又出现了新的问题，验证成功后无法正常跳转主页了，会一直在token验证页面跳转，还有在GitHub上聊天怪怪的，我们是否找个即使聊天工具？

**Comment by U4F5Va6c** [comment]
<img width="1852" alt="image" src="https://github.com/user-attachments/assets/3ac99430-62c3-4a22-98a5-6969dca45963">
验证成功后页面会跳转回这个页面控制台也会报错

**Comment by VariantConst** [comment]
> 还有在GitHub上聊天怪怪的，我们是否找个即使聊天工具？

l 站私信

**Comment by VariantConst** [comment]
v0.1.7 及以上版本解决了该问题
